export const SET_APPLE_COUNT_ON_TREE = "SET_APPLE_COUNT_ON_TREE";

export const SHAKE_TREE = "SHAKE_TREE";
export const DROP_APPLE_FROM_TREE = "DROP_APPLE_FROM_TREE";
export const ADD_APPLE_TO_BASKET = "ADD_APPLE_TO_BASKET";
